# Common settings for all environments
spring.application.name=backend

# Set 'dev' as the default profile for local development
# When running on EC2, we will override this with '-Dspring.profiles.active=prod'
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.web.resources.static-locations=classpath:/static/